BookReadingEventApplication/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookReadingEventApplication.Filters;
using BookReadingEventApplication.Models;

namespace BookReadingEventApplication.Controllers
{
    [UserAuthenticationFilter]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            var Eventbll = new BLL.EventBLL();
            var eventDetail = Eventbll.GetAllEvents();
            EventsWrappper eventWrap = new EventsWrappper();
            
            foreach (var events in eventDetail)
            {
                if (DateTime.Compare(events.eventDate, DateTime.Now) > 0)
                {
                    
                    eventWrap.futureEvents.Add(events);
                }
                else
                {
                    eventWrap.pastEvents.Add(events);
                }
            }
           

            return View(eventWrap);
           
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var eventBll = new BLL.EventBLL();

            var eventDetail = eventBll.GetEventDetails(id);
            var eventInfo = new Event();
            eventInfo.bookTitle = eventDetail.bookTitle;
            eventInfo.eventDate = eventDetail.eventDate;
            eventInfo.description = eventDetail.description;
            eventInfo.eventType = eventDetail.eventType;
            eventInfo.eventDuration = eventDetail.eventDuration;
            eventInfo.location = eventDetail.location;
            eventInfo.startTime = eventDetail.startTime;
            eventInfo.userName = eventDetail.userName;
            eventInfo.eventInvites = eventDetail.eventInvites;
            if (eventDetail == null)
            {
                return HttpNotFound();
            }
            return View(eventInfo);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var eventBll = new BLL.EventBLL();

            var eventDetail = eventBll.GetEventDetails(id);
            eventBll.RemoveEvent(eventDetail);
            return RedirectToAction("Index");

        }
    }
}

BookReadingEventApplication/Controllers/MemberController.cs
using System;
using System.Web.Mvc;
using BookReadingEventApplication.Models;
using System.Net;
using System.Data;
using BookReadingEventApplication.Filters;
using BookEvent.Common;

namespace BookReadingEventApplication.Controllers
{
    [UserAuthenticationFilter]
    public class MemberController : Controller
    {
        // GET: Member
         Interceptor logger = new Interceptor();
         BLL.EventBLL eventBll = new BLL.EventBLL();
        EventDTO eventDto = new EventDTO();
        public ActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEvent(FormCollection form)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            logger.Info("Creating New Events");
            
           

            eventDto.bookTitle = form["bookTitle"].ToString();
            eventDto.location = form["location"].ToString();
            eventDto.eventDate = Convert.ToDateTime(form["eventDate"]);
            eventDto.startTime = form["startTime"];
            eventDto.eventDuration = Convert.ToInt32(form["eventDuration"]);
            eventDto.eventType = form["Event Type"].ToString();
            eventDto.eventInvites = form["eventInvites"];
            eventDto.description = form["description"];
            eventDto.userName = Session["Authenticated"].ToString();
            eventBll.CreateEvent(eventDto);

            return RedirectToAction("Index", "Home");
        }

        public ActionResult MyEvents()
        {
           



            var eventDTO = eventBll.MyEvents(Session["Authenticated"].ToString());
            var eventWrap = new EventsWrappper();
            foreach (var events in eventDTO)
            {
                if (DateTime.Compare(events.eventDate, DateTime.Now) > 0)
                {

                    eventWrap.futureEvents.Add(events);
                }
                else
                {
                    eventWrap.pastEvents.Add(events);
                }
            }


            return View(eventWrap);
        }

        //[Authorize]
        public ActionResult EventsInvitedTo()
        {
           
            //To-Do
            var invites = eventBll.EventInvites(Session["Authenticated"].ToString());
            var eventWrap = new EventsWrappper();
            foreach (var events in invites)
            {
                if (DateTime.Compare(events.eventDate, DateTime.Now) > 0)
                {
                    
                    eventWrap.futureEvents.Add(events);
                }
                else
                {
                    eventWrap.pastEvents.Add(events);
                }
            }


            return View(eventWrap);
        }

        //Get:Edit
        public ActionResult Edit(int? id)
        {

            
            var eventInfo = eventBll.GetEventDetails(id);
            if (eventInfo != null)
            {
                var eventDetail = new Event();
                eventDetail.bookTitle = eventInfo.bookTitle;
                eventDetail.eventDate = eventInfo.eventDate;
                eventDetail.description = eventInfo.description;
                eventDetail.eventType = eventInfo.eventType;
                eventDetail.eventDuration = eventInfo.eventDuration;
                eventDetail.location = eventInfo.location;
                eventDetail.startTime = eventInfo.startTime;
               
                eventDetail.eventInvites = eventInfo.eventInvites;
                return View(eventDetail);
            }
            else
            {
                return RedirectToAction("UserView", "Home");
            }

        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           

            var eventDetail = eventBll.GetEventDetails(id);

            if (TryUpdateModel(eventDetail, "",
               new string[] { "bookTitle", "eventDate", "description", "eventType", "eventDuration", "location", "startTime", "eventInvites" }))
            {
               
                    try
                    {
                        eventBll.EditEvent(eventDetail);
                        if (string.Equals(Session["Authenticated"].ToString(), "Admin"))
                            return RedirectToAction("Index", "Admin");
                        else
                        {
                            return RedirectToAction("UserView", "Home");
                        }
                    }

                    catch (DataException /* dex */)
                    {
                        //Log the error (uncomment dex variable name and add a line here to write a log.
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                    }
                
            }
            return RedirectToAction("UserView", "Home");
        }
    }
}

BookReadingEventApplication/Views/Shared/AccessError.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An attempt to access unauthorize resource</h2>
    </hgroup>
    <div>
        @Html.ActionLink("Back to Home Page", "Index","Home")
    </div>
</body>
</html>

BookReadingEventApplication/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibliognost - My ASP.NET Application</title>
    
    
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Style.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Portal", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Create Event", "CreateEvent", "Member")</li>
                    <li><a href="http://helpdesk.nagarro.com">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav" style="float:right">
                    <li> @Html.ActionLink("Logout", "Logout", "Home")</li>
                    <li> <a href="#">@Session["Authenticated"]</a></li>
                </ul>
             </div>
        </div>
     </div>
    
   
       
   
                   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
    </body>


</html>

BookReadingEventApplication/Views/Shared/Annonymous.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibliognost - My ASP.NET Application</title>
    
    
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Style.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("bibliognost", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    
                    <li><a href="http://helpdesk.nagarro.com">Contact</a></li>
                   
                </ul>
                <ul class="nav navbar-nav" style="float:right">
                    <li> @Html.ActionLink("Login", "Login", "Home")</li>
                </ul>
             </div>
        </div>
     </div>
    
   
       
   
                   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    </body>

</html>

BookReadingEventApplication/Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bibliognost - My ASP.NET Application</title>
    
    
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Style.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("bibliognost", "UserView", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "UserView", "Home")</li>
                    <li>@Html.ActionLink("My Events", "MyEvents", "Member")</li>
                    <li>@Html.ActionLink("Invites", "EventsInvitedTo", "Member")</li>
                    <li>@Html.ActionLink("Create Event", "CreateEvent", "Member")</li>
                    <li><a href="http://helpdesk.nagarro.com">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav" style="float:right">
                    <li> @Html.ActionLink("Logout", "Logout", "Home")</li>
                    <li> <a href="#">@Session["Authenticated"]</a></li>
                </ul>
             </div>
        </div>
     </div>
    
   
       
   
                   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
    </body>


</html>